# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collectC <- function(xs, ys, n) {
    .Call(`_BiDAG_collectC`, xs, ys, n)
}

takefirst <- function(xs, pos) {
    .Call(`_BiDAG_takefirst`, xs, pos)
}

takelast <- function(xs, pos, n) {
    .Call(`_BiDAG_takelast`, xs, pos, n)
}

